name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd ciphers_project
        python manage.py test
    - name: Build and push docker image
      run: |
          docker login --username rohit2905 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/rohit2905/ciphers-service:latest --file Dockerfile .  
          docker push ghcr.io/rohit2905/ciphers-service:latest 

        
